### Questions 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

a1=np.arange(2,51,3)
print(a1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


### Questions 2: Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
list1=[]
list2=[]
for i in range(5):
    a1=int(input())
    list1.append(a1)
print("set of 5 numbers entered to list1 is:",list1)
for j in range(5):
    a2=int(input())
    list2.append(a2)
print("set of 5 numbers entered to list2 is:",list2)
arr1=np.array(list1)
arr2=np.array(list2)
arr3=np.concatenate((arr1,arr2),axis=0)
print("concatenation of arr1 and arr2 is:\n",arr3)
# sorting of arr3 which is concatenated
arr4=np.sort(arr3)
print("After sorting the concatenated array is:\n",arr4)


4
5
6
4
8
set of 5 numbers entered to list1 is: [4, 5, 6, 4, 8]
3
5
2
4
9
set of 5 numbers entered to list2 is: [3, 5, 2, 4, 9]
concatenation of arr1 and arr2 is:
 [4 5 6 4 8 3 5 2 4 9]
After sorting the concatenated array is:
 [2 3 4 4 4 5 5 6 8 9]


### Questions 3: Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr1=np.array([[2,3,5],
              [4,7,2],
              [8,7,6]])
# array dimension
print("Array dimension is",arr1.ndim)

#array size
print("Array size is",np.size(arr1))

Array dimension is 2
Array size is 9


### Questions 4: How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet   
#### Hint: np.newaxis, np.expand_dims

In [5]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr2 = arr1.reshape(2,5)

print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Questions 5: Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

In [6]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
  
arr2 = np.array([[5,6,7],
                 [3,8,9]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((arr1, arr2))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((arr1, arr2)))

Vertical stacking:
 [[1 2 3]
 [4 5 6]
 [5 6 7]
 [3 8 9]]

Horizontal stacking:
 [[1 2 3 5 6 7]
 [4 5 6 3 8 9]]


### Questions 6: How to get unique items and counts of unique items?

In [8]:
arr1=np.array([2,3,4,4,8,8,2,3,3,9,4,2,8,7,12,13,12])
print('Original Array : ' , arr1)

uniquevalues, occurcount = np.unique(arr1, return_counts=True)
print("Unique Values : " , uniquevalues)
print("Count of occurrence: ", occurcount)

Original Array :  [ 2  3  4  4  8  8  2  3  3  9  4  2  8  7 12 13 12]
Unique Values :  [ 2  3  4  7  8  9 12 13]
Count of occurrence:  [3 3 3 1 3 1 2 1]
